spring:
  application:
    name: "gbcc-website-backend"

  datasource:
    url: jdbc:postgresql://localhost:5432/gbcc
    username: username
    password: password
    name: gbcc
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: true

    open-in-view: false

  flyway:
    enabled: true
    locations: classpath:db/migration
    out-of-order: true

app:
  file:
    bucket: storage

  swagger:
    title: "GBCC API"
    description: "Документация API"
    version: "0.1.0"

    servers:
      - url: "http://localhost:8080"
        description: "Local Dev Server"

logging:
  level:
    backend.website.gbcc: DEBUG
    org.springframework.web: INFO
    org.hibernate.SQL: WARN
    org.hibernate.orm.jdbc.bind: WARN